### ISSUE TITLE
Request for requirements.txt

### ISSUE THREAD

**Issue by AaronWarner0** [cvlab-yonsei/Few-Shot-NAS#3]
Hi,

I noticed your project related to few-shot NAS, and it caught my interest. Could you share the requirements.txt to help set up the environment correctly? This would greatly contribute to the project's accessibility and popularity.

Thanks a lot!

**Comment by 50min** [comment]
Hi, thanks for your interest. We have added 'requirements.yml'. Please feel free to take a look.
